name: Liquibase Migration Pipeline

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: taskdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U admin"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Liquibase
        run: |
          curl -L https://github.com/liquibase/liquibase/releases/download/v4.27.0/liquibase-4.27.0.tar.gz -o liquibase.tar.gz
          mkdir liquibase-bin
          tar -xzf liquibase.tar.gz -C liquibase-bin --strip-components=1
          sudo ln -s $PWD/liquibase-bin/liquibase /usr/local/bin/liquibase

      - name: Wait for DB
        run: sleep 10

      - name: Debug
        run: |
          ls -R
          ./liquibase-bin/liquibase --version

      - name: Run Liquibase Migration
        run: |
          ./liquibase-bin/liquibase \
            --url=jdbc:postgresql://localhost:5432/taskdb \
            --username=admin \
            --password=admin \
            --changeLogFile=liquibase/changelog/db.changelog-master.yaml \
            update